### ISSUE TITLE
Exception in thread "main" java.lang.NumberFormatException: For input string: "" (NO_SOURCE_FILE:0) 

### ISSUE THREAD

**Issue by nmilford** [arohner/lein-daemon#5]
Ahoy!

I'm a hapless operations guy tinkering with Clojure.  As an Ops guy lein-daemon is the bee's knees!

I'm working on a learning project [here](https://github.com/nmilford/crybaby) and I am getting the following when I try to daemonize my leiningen project:

```
nathan@sputnik:~/repos/crybaby$ lein daemon start :crybaby
Exception in thread "main" java.lang.NumberFormatException: For input string: "" (NO_SOURCE_FILE:0)
    at clojure.lang.Compiler.eval(Compiler.java:5441)
    at clojure.lang.Compiler.eval(Compiler.java:5392)
    at clojure.core$eval.invoke(core.clj:2382)
    at clojure.main$eval_opt.invoke(main.clj:235)
    at clojure.main$initialize.invoke(main.clj:254)
    at clojure.main$script_opt.invoke(main.clj:270)
    at clojure.main$main.doInvoke(main.clj:354)
    at clojure.lang.RestFn.invoke(RestFn.java:512)
    at clojure.lang.Var.invoke(Var.java:385)
    at clojure.lang.AFn.applyToHelper(AFn.java:185)
    at clojure.lang.Var.applyTo(Var.java:482)
    at clojure.main.main(main.java:37)
Caused by: java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:493)
    at java.lang.Integer.parseInt(Integer.java:514)
    at leiningen.daemon_runtime$get_pid.invoke(daemon_runtime.clj:78)
    at leiningen.daemon$pid_present_QMARK_.invoke(daemon.clj:26)
    at leiningen.daemon$start_main.doInvoke(daemon.clj:40)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.core$apply.invoke(core.clj:544)
    at leiningen.daemon$daemon.doInvoke(daemon.clj:120)
    at clojure.lang.RestFn.invoke(RestFn.java:439)
    at clojure.lang.Var.invoke(Var.java:373)
    at clojure.lang.AFn.applyToHelper(AFn.java:167)
    at clojure.lang.Var.applyTo(Var.java:482)
    at clojure.core$apply.invoke(core.clj:542)
    at leiningen.core$apply_task.invoke(core.clj:262)
    at leiningen.core$_main.doInvoke(core.clj:329)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.core$apply.invoke(core.clj:542)
    at leiningen.core$_main.invoke(core.clj:332)
    at user$eval42.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:5425)
    ... 11 more
```

I have in my project.clj:

```
  :dev-dependencies [[lein-daemon "0.4.0"]]
```

and

```
  :daemon {:crybaby {:ns crybaby.core
                     :pidfile "run/crybaby.pid"}}
```

I am working in Ubuntu 12.04, Clojure 1.4.0 and Leiningen 1.7.1 on Java 1.6.0_24 OpenJDK 64-Bit Server VM.

I must be overlooking some mundane detail, but I haven't quite gotten the knack for parsing Clojure stack traces...

Have you any thoughts?

**Comment by arohner** [comment]
Hey there. I was just having a conversation with another Clojure guy about lein daemon. The last version that lein-daemon currently works on is 1.6.1.1, because lein 1.7 changed the way it exposes ant tasks to plugins. Sean Corfield and I are looking into solutions for making this work in lein2.

**Comment by nmilford** [comment]
Drama!  I'll follow this repo and cross my fingers :)

Just to be thorough, I got through the error above.

I changed :pidfile from "run/crybaby.pid" to "crybaby.pid" and it passed, however now I get this:

```
nathan@sputnik:~/repos/crybaby$ lein daemon start :crybaby
forking :crybaby
Exception in thread "main" java.lang.Exception: unimplemented method setsid (NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:5440)
    at clojure.lang.Compiler.eval(Compiler.java:5415)
    at clojure.lang.Compiler.eval(Compiler.java:5391)
    at clojure.core$eval.invoke(core.clj:2382)
    at clojure.main$eval_opt.invoke(main.clj:235)
    at clojure.main$initialize.invoke(main.clj:254)
    at clojure.main$null_opt.invoke(main.clj:279)
    at clojure.main$main.doInvoke(main.clj:354)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:369)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.Var.applyTo(Var.java:482)
    at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: unimplemented method setsid
    at leiningen.daemon_runtime$fn__11$fn__30.invoke(daemon_runtime.clj:13)
    at leiningen.daemon_runtime.proxy$java.lang.Object$POSIXHandler$fc51493.unimplementedError(Unknown Source)
    at org.jruby.ext.posix.JavaPOSIX.unimplementedInt(JavaPOSIX.java:256)
    at org.jruby.ext.posix.JavaPOSIX.setsid(JavaPOSIX.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:90)
    at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:265)
    at leiningen.daemon_runtime$init.doInvoke(daemon_runtime.clj:55)
    at clojure.lang.RestFn.invoke(RestFn.java:439)
    at user$eval2060.invoke(NO_SOURCE_FILE:1)
    at clojure.lang.Compiler.eval(Compiler.java:5424)
    ... 12 more
```

Looks like it is choking on the jruby posix setsid method.

**Comment by arohner** [comment]
This should work in 0.5.3
